### PR TITLE
Addition of Connection ID parameter to output log entries

### PR DESCRIPTION
**Pull request by yzninja**
This pull request is fix to address issue #33. 
There should now have one commit for the Connection ID parameter addition to the log entries. Let me know if there are any issues. Thanks.

### CODE REVIEW

**Comment by chadbrubaker** [comment]
Looks like you might need a rebase onto the current dev branch.
$ git rebase <feature> upstream/dev

at the end if you run
$ git log upstream..<feature branch>
you should just see one commit.

Or I can cherry-pick it and upload the PR for you?(the commit will still be yours, I'll just be making the PR)

**Comment by yzninja** [comment]
Thanks for the prompt reply Chad. It would be probably easier for you to cherry pick it please. I still have my learner's plates on :)

**Comment by chadbrubaker** [comment]
Moving to https://github.com/google/nogotofail/pull/70

**Comment by chadbrubaker** [comment]
Merged.

I noticed there is another PR from you that I forgot to look at, its 4 AM
here but I'll try and take a look at it tomorrow, sorry!

**Comment by yzninja** [comment]
No worries. There was another pull request that I closed and replaced with this one - it was easier to start a new one.
The PR I closed was #68.
https://github.com/google/nogotofail/pull/68#issuecomment-84092553

**Pull request closed without merging**
