### PR TITLE
Added instructions to the GCE readme documentation

### PR DESCRIPTION
**Pull request by yzninja**
I added some suggestions to the GCE readme document that may make the setup clearer for others. Please feel free to change it if needed.

### CODE REVIEW

**Comment by yzninja** [comment]
Perhaps "Options for the mitm daemon reside in the /opt/nogotofail directory"? 

I think the wording for the "Available configuration options" could be improved, I personally would find it useful to know these  items i.e. configuration file is mitm.conf,  trusted-cert.pem is used for invalid host name attacks.

Oops ... server.crt isn't used for the self-signed certificate attack, it's for encrypting client/server traffic. I have to fix that.

**Comment by yzninja** [comment]
I'll update the wording in the document. Let me know what you think after the updates.

I agree the "available configuration options" does seem out of place - I personally like one place in the document that explains the configuration options (but maybe I am repeating some info from the getting_started doco). The two most confusing things I found in the GCE setup were - finding the location of the .conf file, and start/stopping the mitm daemon.

**Comment by klyubin** [comment]
Re: "available configuration options" I only meant that that particular sentence appears extraneous. The text following it is OK.

**Comment by yzninja** [comment]
I have update the help document. Hopefully it reads better now.

**Comment by yzninja** [comment]
Thanks Alex. About the location of the mitm.conf file on GCE? I was only able to connect from my mitm client to the server when mitm.conf was in /etc/nogotofail/.
In this pull request I specified /opt/nogotofail/mitm.conf.

**Comment by klyubin** [comment]
Oops. The correct location is /etc/nogotofail/mitm.conf.

**Comment by yzninja** [comment]
No worries I'll update the readme.md. 

Is /etc/nogotofail also the correct location for the "server.crt" and "trusted-cert.pem" files as well?

**Comment by klyubin** [comment]
There's no server.crt. The setup script uses
/etc/nogotofail/mitm_controller_cert_and_key.pem.

trusted-cert.pem needs to stay in /opt/nogotofail because of how nogotofail
currently loads it. Otherwise, it would've made much more sense for it to
be under /etc/nogotofail.

Alex

**Comment by yzninja** [comment]
I fixed up the path for mitm.conf (to /etc/nogotofail/mitm.conf) and removed the reference to server.crt. Should I open a new pull request for the update or is it possible to reopen this one?

**Comment by klyubin** [comment]
This pull request's merged already. The easiest way forward is to create a
new one. Thanks in advance!

**Comment by yzninja** [comment]
In my local dev branch I have squashed the fixes into the original commit that was merged.
Is that ok, or do you want a new (separate) commit for the latest fixes?

**Comment by klyubin** [comment]
Whatever works. I suspect it'll be a separate commit in this repository anyway -- this repository already contains part of your squashed commit.

**Pull request merged**
